version: '2'
services:
  mysql:
    image: 'mysql:5.7'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root

  memcached:
    image: 'memcached:1.6.6-alpine'
    ports:
      - '11211:11211'

  redis:
    image: 'redis:6.0.5-alpine'
    ports:
      - '6379:6379'

  php:
    build: docker/php
    links:
      - mysql
      - memcached
      - redis
    volumes:
      - './www:/var/www/codex.media'

  nginx:
    image: 'nginx:1.19.1-alpine'
    ports:
      - '8090:8080'
    links:
      - php
    volumes:
      - './docker/nginx-codex.conf:/etc/nginx/conf.d/codex.conf'
    volumes_from:
      - php

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    ports:
      - '8091:80'
    environment:
      UPLOAD_LIMIT: 10000000
      PMA_ARBITRARY: 1