version: '2'
services:
  mysql:
    image: 'mysql:5.7'
    volumes:
      - ./dump/mysql:/dump
      - mysqldata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root

  memcached:
    image: 'memcached:1.6.6-alpine'
    ports:
      - "11211:11211"

  redis:
    image: 'redis:6.0.5-alpine'
    command: ["redis-server", "--save 900 1", "--save 300 10", "--save 60 10000"]
    volumes:
      - ./dump/redis:/data
    ports:
      - "6379:6379"

  php:
    build:
      dockerfile: 'docker/php/prod.Dockerfile'
      context: '.'
    links:
      - mysql
      - memcached
      - redis
    volumes:
      - './www:/var/www/codex.media'

  nginx:
    image: 'nginx:1.19.1-alpine'
    ports:
      - "8880:8080"
    links:
      - php
    volumes:
      - './docker/codex-media.conf:/etc/nginx/conf.d/codex.conf'
    volumes_from:
      - php

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    ports:
      - "8881:80"
    environment:
      UPLOAD_LIMIT: 52428800
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root

volumes:
  mysqldata: